---
sidebar: sidebar 
permalink: task-replicating-data.html 
keywords: ontap, cluster, discover, manage, BlueXP, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, schedule, relationship, max transfer, maximum transfer rate, rate, transfer rate, intercluster lif, replication requirement, requirements, disaster recovery, DR, archive, archiving, retention, amazon fsx for ontap, fsx for ontap 
summary: ONTAP 시스템 간 데이터 복제는 일회성 데이터 전송 또는 재해 복구나 장기 보존을 위한 정기적인 일정 설정을 통해 수행할 수 있습니다. 예를 들어, 온프레미스 ONTAP 시스템에서 Cloud Volumes ONTAP으로의 재해 복구를 위한 데이터 복제를 설정할 수 있습니다. 
---
= NetApp Replication 에서 데이터 복제 설정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Replication 사용하면 데이터 전송을 위한 일회성 데이터 복제나 재해 복구 또는 장기 보존을 위한 반복 일정을 선택하여 ONTAP 시스템 간에 데이터를 복제할 수 있습니다.  예를 들어, 재해 복구를 위해 온프레미스 ONTAP 시스템에서 Cloud Volumes ONTAP 으로 데이터 복제를 설정할 수 있습니다.



[[step-1-review-data-replication-requirements]]
== 1단계: 데이터 복제 요구 사항 검토

데이터를 복제하기 전에 Cloud Volumes ONTAP, 온프레미스 ONTAP 클러스터 또는 Amazon FSx for ONTAP에 대한 특정 요구 사항이 충족되는지 확인해야 합니다.

시스템:: 아직 수행하지 않았다면 데이터 복제 관계에서 소스와 대상에 대한 시스템을 만들어야 합니다.
+
--
* https://docs.netapp.com/us-en/storage-management-fsx-ontap/start/task-getting-started-fsx.html["Amazon FSx for ONTAP 시스템 생성"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-overview-cvo.html["Cloud Volumes ONTAP 시스템 생성"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-adding-systems.html["기존 Cloud Volumes ONTAP 시스템 추가"^]
* https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["ONTAP 클러스터를 찾아보세요"^]


--
버전 요구 사항:: 데이터를 복제하기 전에 소스 및 대상 볼륨이 호환되는 ONTAP 버전을 실행하고 있는지 확인해야 합니다.
+
--
https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["SnapMirror 관계에 대한 호환 ONTAP 버전 보기"^]

--
Cloud Volumes ONTAP 에 대한 특정 요구 사항::
+
--
* 인스턴스의 보안 그룹에는 필수 인바운드 및 아웃바운드 규칙이 포함되어야 합니다. 구체적으로는 ICMP 및 포트 11104와 11105에 대한 규칙이 포함됩니다.
+
이러한 규칙은 미리 정의된 보안 그룹에 포함됩니다.

* 서로 다른 서브넷에 있는 두 개의 Cloud Volumes ONTAP 시스템 간에 데이터를 복제하려면 서브넷을 함께 라우팅해야 합니다(이는 기본 설정입니다).
* 서로 다른 클라우드 공급자의 두 Cloud Volumes ONTAP 시스템 간에 데이터를 복제하려면 가상 네트워크 간에 VPN 연결이 필요합니다.


--
ONTAP 클러스터에 대한 특정 요구 사항::
+
--
* 활성화된 SnapMirror 라이선스를 설치해야 합니다.
* 클러스터가 사내에 있는 경우 회사 네트워크에서 클라우드의 가상 네트워크로 연결되어야 합니다.  이는 일반적으로 VPN 연결입니다.
* ONTAP 클러스터는 추가적인 서브넷, 포트, 방화벽 및 클러스터 요구 사항을 충족해야 합니다.
+
https://docs.netapp.com/us-en/ontap/peering/prerequisites-cluster-peering-reference.html#connectivity-requirements["ONTAP 설명서에서 클러스터 피어링에 대한 필수 구성 요소 보기"^]



--
Amazon FSx for ONTAP 에 대한 특정 요구 사항::
+
--
* Cloud Volumes ONTAP 이 관계에 포함된 경우 VPC 피어링을 활성화하거나 Transit Gateway를 사용하여 VPC 간 연결을 보장합니다.
* 온프레미스 ONTAP 클러스터가 관계에 포함된 경우, Direct Connect 또는 VPN 연결을 사용하여 온프레미스 네트워크와 AWS VPC 간의 연결을 확보하십시오.


--




[[step-2-replicate-data-between-systems]]
== 2단계: 시스템 간 데이터 복제

일회성 데이터 복제를 선택하면 클라우드로 데이터를 이동하거나 클라우드에서 데이터를 가져오는 데 도움이 되고, 반복 일정을 선택하면 재해 복구나 장기 보존에 도움이 되는 방식으로 데이터를 복제할 수 있습니다.

.단계
. 탐색 메뉴에서 *저장소 > 관리*를 선택합니다.
. 시스템 페이지에서 소스 볼륨이 포함된 시스템을 선택하고 볼륨을 복제할 시스템으로 끌어온 다음 *복제*를 선택합니다.
+
나머지 단계에서는 Cloud Volumes ONTAP 또는 온프레미스 ONTAP 클러스터 간의 동기화 관계를 생성하는 방법을 예시로 보여줍니다.

. *소스 및 대상 피어링 설정*: 이 페이지가 나타나면 클러스터 피어 관계에 대한 모든 클러스터 간 LIF를 선택합니다.
+
클러스터 간 네트워크는 클러스터 피어가 _페어별 풀 메시 연결_을 갖도록 구성되어야 합니다. 즉, 클러스터 피어 관계에 있는 각 클러스터 쌍이 모든 클러스터 간 LIF 간에 연결성을 가져야 합니다.

+
이 페이지는 여러 LIF가 있는 ONTAP 클러스터가 소스 또는 대상인 경우 나타납니다.

. *소스 볼륨 선택*: 복제하려는 볼륨을 선택합니다.
. *대상 디스크 유형 및 계층화*: 대상이 Cloud Volumes ONTAP 시스템인 경우 대상 디스크 유형을 선택하고 데이터 계층화를 활성화할지 여부를 선택합니다.
. *대상 볼륨 이름*: 대상 볼륨 이름을 지정하고 대상 집계를 선택합니다.
+
대상이 ONTAP 클러스터인 경우 대상 스토리지 VM도 지정해야 합니다.

. *최대 전송 속도*: 데이터를 전송할 수 있는 최대 속도(초당 메가바이트)를 지정합니다.
+
전송 속도를 제한해야 합니다.  무제한 요금은 다른 애플리케이션의 성능에 부정적인 영향을 미칠 수 있으며, 인터넷 성능에도 영향을 미칠 수 있습니다.

. *복제 정책*: 기본 정책을 선택하거나 *추가 정책*을 선택한 다음 고급 정책 중 하나를 선택합니다.
+
도움이 필요하면,link:concept-replication-policies.html["복제 정책에 대해 알아보세요"] .

+
사용자 정의 백업(SnapVault) 정책을 선택하는 경우 해당 정책과 연관된 레이블은 소스 볼륨의 스냅샷 복사본 레이블과 일치해야 합니다.  자세한 내용은link:concept-backup-policies.html["백업 정책이 어떻게 작동하는지 알아보세요"] .

. *일정*: 일회성 사본이나 반복 일정을 선택하세요.
+
여러 가지 기본 일정을 사용할 수 있습니다.  다른 일정을 원하는 경우 시스템 관리자를 사용하여 _대상_ 클러스터에 새 일정을 만들어야 합니다.

. *검토*: 선택 사항을 검토하고 *진행*을 선택합니다.


.결과
NetApp Replication 데이터 복제 프로세스를 시작합니다.  NetApp Replication 에서 볼륨 관계에 대한 세부 정보를 볼 수 있습니다.
